services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres:17.2
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: bricolage
      POSTGRES_PASSWORD: pos123
      POSTGRES_DB: bricolage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bricolage-network
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "bricolage" ]
        interval: 10s
        timeout: 5s
        retries: 5

  db-migration:
    image: liquibase/liquibase
    container_name: db-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND=update
      - LIQUIBASE_URL=jdbc:postgresql://postgres-container:5432/bricolage
      - LIQUIBASE_USERNAME=bricolage
      - LIQUIBASE_PASSWORD=pos123
    volumes:
        - ./src/main/resources/db:/liquibase/db
    entrypoint: [ "liquibase" ]
    command:
        - "--changeLogFile=db/db.changelog-master.xml"
        - "--url=jdbc:postgresql://postgres-container:5432/bricolage"
        - "--username=bricolage"
        - "--password=pos123"
        - "update"
    networks:
      - bricolage-network

  spring-app:
    build: .
    container_name: spring-app-container
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_POSTGRES_URL: jdbc:postgresql://postgres-container:5432/bricolage
      SPRING_DATASOURCE_POSTGRES_USERNAME: bricolage
      SPRING_DATASOURCE_POSTGRES_PASSWORD: pos123
    networks:
      - bricolage-network

volumes:
  postgres_data:

networks:
    bricolage-network:
        driver: bridge